@startuml

participant "Attester" as A
participant "Relying Party" as RP
participant "Verifier" as V

group Background Check pattern
	A -> RP: Evidence
	RP -> V: Evidence
	V -> RP: Attestation Results
end

@enduml
